language: r

sudo: required

# Be strict when checking our package
warnings_are_errors: true

r-packages:
- GetoptLong
- colorspace
- RColorBrewer
- testthat
- knitr
- markdown
- dendextend

bioc_packages:
- GenomicRanges
- HilbertVis

r_github_packages:
- jokergoo/circlize
- jokergoo/HilbertCurve
- jimhester/covr

r_check_args: --no-build-vignettes --no-vignettes

after_success:
  - Rscript -e 'library(covr);codecov()'
  
